# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    access_denied_url: 'home'

    #Choix du mode d'encryptage

    encoders:
        AppBundle\Entity\Utilisateur: bcrypt

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
    #defini l'id des comptes comme étant le mot de passe
        our_users:
            entity: { class: AppBundle\entity\Utilisateur, property: emailUtilisateur}

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            #service utilisé pour authentifier l'utilisateur
            guard:
                authenticators:
                    - app.security.login_form_authenticator
            # définis la route à utiliser en cas de logoout (traitement automatique
            logout:
                path: /Utilisateur/logout
            # activate different ways to authenticate

#
#MIDDLEWARES
#
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/accountManager/edit, roles: ROLE_USER }
        - { path: ^/commande/gestionCommande, roles: ROLE_ADMIN }
        - { path: ^/commande/validerCommande, roles: ROLE_ADMIN }
        - { path: ^/commande/ficheCommande, roles: [ROLE_ADMIN, ROLE_USER] }
        - { path: ^/commande/afficherCommandes, roles: ROLE_USER }
        - { path: ^indexAdmin, roles: ROLE_ADMIN }
