# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html

parameters:

services:

#
# service utilisé pour l'authentification
#
    app.security.login_form_authenticator:
        class: AppBundle\Security\LoginFormAuthenticator
        autowire: true

#
# Classe utilisée pour crypter le mot de passe. Il existe des choses préfaites, on a préféré les faire
# de nous même afin d'en observer le fonctionnement
#
    app.doctrine.hash_password_listener:
        class: AppBundle\Doctrine\HashPasswordListener
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }